### ISSUE TITLE
Dark Mode: Checkbox stars are misaligned

### ISSUE THREAD

**Issue by Patabugen** [Emrie-Candera/Bubble-Space-Theme#26]
Obsidian Version: 1.1.9
Bubble-Space-Theme version: 1.6

When in dark mode the lovely stars which make up checklists became misaligned (at some point in the last few weeks/months, I can't really remember when).

I don't know enough about Obsidian themes to submit a PR, but I have made a little workaround which works for me, might work for you and may be useful for a future update.

I simply added a [CSS Snippet](https://projecteme.medium.com/how-to-customise-your-own-obsidian-css-in-3-steps-ae319e53f5d4) to re-align the stars.

## Before

![image](https://user-images.githubusercontent.com/196795/212972473-00087ad8-fd71-4a1a-8910-dcbeed119cb8.png)

## Workaround

```css
.task-list-item-checkbox::before,
.task-list-item-checkbox:checked::before {
    top: -13px;
    position: relative;
}
```

## After:
![image](https://user-images.githubusercontent.com/196795/212972509-9bab81a2-4cc4-473c-840f-cdc23d466966.png)
