### ISSUE TITLE
Seems it doesn't work well on LP mode

### ISSUE THREAD

**Issue by Quorafind** [Emrie-Candera/Bubble-Space-Theme#3]
![image](https://user-images.githubusercontent.com/13215013/145804353-b3979635-09d9-4eb5-bcf5-ae91753a3004.png)

**Comment by Emrie-Candera** [comment]
Hi! I'm actually not an insider so unfortunately won't be able to test in for LP mode right now 😢

**Comment by Aaron-Bopp** [comment]
The latest insider changed bullets again, so here's my temp fix if you want to use it as a css snippet (hopefully this is helpful for updating the theme as well 😄)
```css
.theme-dark li::marker{
    content: '★'; 
    font-size: 13px;
    color: var(--gold1); 
}

.theme-dark .mod-cm6 .HyperMD-list-line .list-bullet::after,
.theme-dark .mod-cm6 span.list-bullet::after {
    content: '★'; 
    font-size: 11px;
    color: var(--gold1); 
    visibility: visible;
    position: absolute;
    top: 4px;
    left: -2px;
}
.theme-light.mod-cm6 .HyperMD-list-line .list-bullet::after,
.theme-light .mod-cm6 span.list-bullet::after {
    visibility: hidden !important;
    padding-right: 4px;
} 

.theme-light .mod-cm6 .HyperMD-list-line .list-bullet::after,
.theme-light .mod-cm6 span.list-bullet::after {
    content: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA8AAAAPCAYAAAA71pVKAAAABmJLR0QA/wD/AP+gvaeTAAABmklEQVQokaWSMWiTURRGz3f/pNWmixWi7q4OLTi5mMFCHezg0gZjBRd17+ri6CYUnAQbSWvBwcGpYgX3VkUEF9eaoHUxQqP/+xxi6k/ULP3G+9555z7uhUNEw4UTjbsVVFk0qQZxEnlX1kvcXWs3l7v/hatLK7NYTUEZeduOr1I6hpmx3CMvNTqPbmz+BVeXVmZJekbwNEvRyiOfdCJC8TmssTxSneR5nF0cPKBBq1blI+JVltxKiuvGc+B1Ea2BwPI17HPy99Pt5nI3+v7KoqCcpfgNprNy3C6l0kbxW1mKlmAcJhYAAsCkGvJ2biaN5yTdQ36dR/pZhJPcw9pxUDuAIaok7SlcAj3J8uzdiAl9EVQLcOoQngI6gofDxqEcN3QOYBFbWDNhjY2A6J972o4Xf8zurlmpl0eqj4LzSHWj/fKRWAfIALpvN39Uzlx6g9IdxNHM8d4iLxqTfBV7XtLlTw9ufuh3XEj1yv0LRL4qGMfasbQnewo8bbQv0Wiv3no+uP/v3WZiwcF5wSnDrh1b4W+Ph3f7UPkFeM+6vmvDCTwAAAAASUVORK5CYII="); 
    visibility: visible !important;
    color: var(--gold1); 
    position: absolute;
    top: 4px;
    left: -4px;
} 

.theme-light li::marker{
    content: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA8AAAAPCAYAAAA71pVKAAAABmJLR0QA/wD/AP+gvaeTAAABmklEQVQokaWSMWiTURRGz3f/pNWmixWi7q4OLTi5mMFCHezg0gZjBRd17+ri6CYUnAQbSWvBwcGpYgX3VkUEF9eaoHUxQqP/+xxi6k/ULP3G+9555z7uhUNEw4UTjbsVVFk0qQZxEnlX1kvcXWs3l7v/hatLK7NYTUEZeduOr1I6hpmx3CMvNTqPbmz+BVeXVmZJekbwNEvRyiOfdCJC8TmssTxSneR5nF0cPKBBq1blI+JVltxKiuvGc+B1Ea2BwPI17HPy99Pt5nI3+v7KoqCcpfgNprNy3C6l0kbxW1mKlmAcJhYAAsCkGvJ2biaN5yTdQ36dR/pZhJPcw9pxUDuAIaok7SlcAj3J8uzdiAl9EVQLcOoQngI6gofDxqEcN3QOYBFbWDNhjY2A6J972o4Xf8zurlmpl0eqj4LzSHWj/fKRWAfIALpvN39Uzlx6g9IdxNHM8d4iLxqTfBV7XtLlTw9ufuh3XEj1yv0LRL4qGMfasbQnewo8bbQv0Wiv3no+uP/v3WZiwcF5wSnDrh1b4W+Ph3f7UPkFeM+6vmvDCTwAAAAASUVORK5CYII="); 
    font-size: 13px;
    color: var(--gold1); 
    padding-top: 4px;
}
.theme-light span.cm-formatting-list-ul:after {
    visibility: hidden !important;
}
```
